% Provide first, middle, and last name as shown on Canvas
% FIRST = ...
% MIDDLE = ...
% LAST = ...

files = {
  'recurrent_tanh_forward.m', ...
  'recurrent_tanh_backward.m', ...
  'recurrent_lstm_forward.m', ...
  'recurrent_lstm_backward.m', ...
  'lstm.m', ...
  'create_rnn.m', ...
  'basic_rnn.m', ...
  'lstm_rnn.m', ...
  'basic_rnn_100.mat', ...
  'lstm_rnn_95.mat'
};

zip('Alexander_R_Wolf_HW4.zip', files);
